# The login of a member of the team.
# Used to customize the name of the VMs.
A_LOGIN = "ygaude"
# The current part of the project.
PART = 2

# The name of the server VM.
SERVER_NAME = "#{A_LOGIN}S"

SERVER_IP = "192.168.56.110"

Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/jammy64"

    config.vm.provider "virtualbox" do |v|
        # Set the VM name.
        v.customize ["modifyvm", :id, "--name", "#{SERVER_NAME}-P#{PART}"]
        # Disable gui
        v.gui = false
        # Config cpu number
        v.cpus = 2
        # Config RAM
        v.memory = 2048
    end

    # Set the hostname of the VM.
    config.vm.hostname = SERVER_NAME

    # Configure the IP address of the VM.
    print "[#{SERVER_NAME}] Using IP #{SERVER_IP}\n"
    config.vm.network "private_network", ip: SERVER_IP

    # Install K3s in controller mode.
    config.vm.provision "shell",
        name: "Install K3s in controller mode",
        run: "once",
        path: "https://get.k3s.io/",
        sha256: "704f918bc8bc56329dce985ee7964cceff3f53d3580beff99ee85d8e7da94638",
        args: [
            "server",
            "--node-name=#{SERVER_NAME}-controller",
            "--tls-san=#{SERVER_IP}",
            "--node-ip=#{SERVER_IP}"
        ]

    config.vm.provision "shell",
        name: "Copy kubectl config file",
        run: "once",
        inline: <<-SHELL
            sed 's;server: https://127.0.0.1:6443$;server: https://#{SERVER_IP}:6443;' /etc/rancher/k3s/k3s.yaml | tee /vagrant/kubectl.config.yml
        SHELL
end
