# The login of a member of the team.
# Used to customize the name of the VMs.
A_LOGIN = "ygaude"
# The current part of the project.
PART = 1

# The name of the server VM.
SERVER_NAME = "#{A_LOGIN}S"
# The name of the server worker VM.
SERVER_WORKER_NAME = "#{A_LOGIN}SW"

BASE_VM_IP = "192.168.56"
SERVER_IP = "#{BASE_VM_IP}.110"
SERVER_WORKER_IP = "#{BASE_VM_IP}.111"

K3S_NODE_TOKEN_FILENAME = "k3s_token"

# Create a file that will hold the k3s token only if it doesn't exist.
if File.file?(K3S_NODE_TOKEN_FILENAME) == false
    File.open(K3S_NODE_TOKEN_FILENAME, "w") do | file |
        file << SecureRandom.hex(32) << "\n"
    end
end

Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/jammy64"

    # Configure the Server VM.
    config.vm.define SERVER_NAME do |control|

        control.vm.provider "virtualbox" do |v|
            # Set the VM name.
            v.customize ["modifyvm", :id, "--name", "#{SERVER_NAME}-P#{PART}"]
            # Disable gui
            v.gui = false
            # Config cpu number
            v.cpus = 2
            # Config RAM
            v.memory = 2048
        end
        # Set the hostname of the VM.
        control.vm.hostname = SERVER_NAME

        # Configure the IP address of the VM.
        print "[#{SERVER_NAME}] Using IP #{SERVER_IP}\n"
        control.vm.network "private_network", ip: SERVER_IP

        # Install K3s in controller mode.
        control.vm.provision "shell",
            name: "Install K3s in controller mode",
            run: "once",
            path: "https://get.k3s.io/",
            sha256: "704f918bc8bc56329dce985ee7964cceff3f53d3580beff99ee85d8e7da94638",
            args: [
                "server",
                "--node-name=#{SERVER_NAME}-controller",
                "--token-file=/vagrant/#{K3S_NODE_TOKEN_FILENAME}",
                "--bind-address=#{SERVER_IP}",
                "--https-listen-port=6443",
                "--tls-san=#{SERVER_IP}",
                "--node-external-ip=#{SERVER_IP}"
            ]
    end

    # Configure the Server Worker VM.
    config.vm.define SERVER_WORKER_NAME do |control|
        control.vm.provider "virtualbox" do |v|
            # Set the VM name.
            v.customize ["modifyvm", :id, "--name", "#{SERVER_WORKER_NAME}-P#{PART}"]
            # Config cpu number
            v.cpus = 2
            # Config RAM
            v.memory = 2048
        end
        # Set the hostname of the VM.
        control.vm.hostname = SERVER_WORKER_NAME

        # Configure the IP address of the VM.
        print "[#{SERVER_WORKER_NAME}] Using IP #{SERVER_WORKER_IP}\n"
        control.vm.network "private_network", ip: SERVER_WORKER_IP

        # Install K3s in agent mode.
        control.vm.provision "shell",
            name: "Install K3s in agent mode",
            run: "once",
            path: "https://get.k3s.io/",
            sha256: "704f918bc8bc56329dce985ee7964cceff3f53d3580beff99ee85d8e7da94638",
            args: [
                "agent",
                "--server=https://#{SERVER_IP}:6443",
                "--node-name=#{SERVER_WORKER_NAME}-agent",
                "--token-file=/vagrant/#{K3S_NODE_TOKEN_FILENAME}"
            ]
    end
end
