# The login of a member of the team.
# Used to customize the name of the VMs.
A_LOGIN = "ygaude"
# The current part of the project.
PART = 3

# The name of the server VM.
SERVER_NAME = "#{A_LOGIN}S"

SERVER_IP = "192.168.56.110"

ANSIBLE_PACKAGE_VERSION = "6.3.0"
ANSIBLE_CORE_VERSION = "2.13.5"

Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/jammy64"

    config.vm.provider "virtualbox" do |v|
        # Set the VM name.
        v.customize ["modifyvm", :id, "--name", "#{SERVER_NAME}-P#{PART}"]
        # Disable gui
        v.gui = false
        # Config cpu number
        v.cpus = 2
        # Config RAM
        v.memory = 2048
    end

    # Set the hostname of the VM.
    config.vm.hostname = SERVER_NAME

    # Configure the IP address of the VM.
    print "[#{SERVER_NAME}] Using IP #{SERVER_IP}\n"
    config.vm.network "private_network", ip: SERVER_IP

    config.vm.provision "shell",
        name: "Install requirement for ansible",
        run: "once",
        inline: <<-SHELL
            set -eux
            export DEBIAN_FRONTEND=noninteractive
            sudo apt-get update
            sudo apt-get install -y \
                python3-{dev,venv,pip} \
                build-essential \
                curl \
                git \
                lib{ssl,ffi}-dev
            python3 -m pip install ansible==#{ANSIBLE_PACKAGE_VERSION}
        SHELL

    # Install requirement for K3D.
    config.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "play_k3d.yml"
        ansible.install = false
        ansible.version = "[core #{ANSIBLE_CORE_VERSION}]"
        ansible.raw_arguments = [
            "--extra-vars", "server_ip=#{SERVER_IP}"
        ]
    end
end
